import type { Institution, UserProfile, Club, ClubMember, EventItem, EventRegistration, IssuedCertificate, RecruitmentApplicant } from '../types';

export const mockInstitution: Institution = {
  id: 'inst-sanjivani-1',
  name: 'Sanjivani College of Engineering, Kopargaon',
  shortName: 'Sanjivani COE',
  slug: 'sanjivani-coe',
  domain: 'sanjivani.edu.in',
  logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=160&q=80',
  location: 'SRES Campus, Kopargaon, Ahmednagar, Maharashtra, India',
  naacCycle: 'Autonomous Institute (NAAC A Grade, NBA Accredited)',
  iqacDirector: 'Dr. A. G. Thakur',
};

export const mockStudents: UserProfile[] = [
  {
    id: 'usr-aditi-1',
    fullName: 'Aditi Bhor',
    username: 'aditi.bhor',
    email: 'aditi.bhor26@sanjivani.edu.in',
    phone: '+91 98234 56781',
    prnRollNo: 'SCOE-24-CE-082',
    department: 'Civil Engineering',
    graduationYear: 2027,
    division: 'E',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    bio: '2nd Year Civil Engg @ Sanjivani | Network Team @ SARC & CESA | Smart Infra & AI Enthusiast',
    linkedinUrl: 'https://linkedin.com/in/aditi-bhor',
    githubUrl: 'https://github.com/aditibhor',
    volunteerHours: 38,
  },
  {
    id: 'usr-rohan-2',
    fullName: 'Rohan Sharma',
    username: 'rohan.sharma',
    email: 'rohan.s25@sanjivani.edu.in',
    phone: '+91 98111 22334',
    prnRollNo: 'SCOE-23-COMP-014',
    department: 'Computer Engineering',
    graduationYear: 2026,
    division: 'B',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    bio: 'Lead Organizer @ CSI & Coding Club Sanjivani | Distributed Systems & Full-Stack Architect',
    linkedinUrl: 'https://linkedin.com/in/rohan-sharma-tech',
    githubUrl: 'https://github.com/rohansharma',
    volunteerHours: 72,
  },
  {
    id: 'usr-tanvi-3',
    fullName: 'Tanvi Deshmukh',
    username: 'tanvi.d',
    email: 'tanvi.d27@sanjivani.edu.in',
    phone: '+91 97654 32109',
    prnRollNo: 'SCOE-25-ECE-045',
    department: 'Electronics & Computer Engineering',
    graduationYear: 2028,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    bio: '1st Year ECE @ Sanjivani | Team Robocon hardware designer | Embedded IoT hobbyist',
    volunteerHours: 14,
  },
];

export const mockClubs: Club[] = [
  {
    id: 'club-csi-1',
    institutionId: 'inst-sanjivani-1',
    name: 'CSI & Coding Club Sanjivani',
    slug: 'csi-sanjivani',
    category: 'Technical',
    logoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=120&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    description: 'Premier technical body of Sanjivani College of Engineering organizing national hackathons, open-source bootcamps, and algorithmic competitions.',
    instagramHandle: '@csi_sanjivani',
    facultyAdvisor: 'Prof. D. B. Kshirsagar',
    presidentName: 'Rohan Sharma',
    membersCount: 215,
    eventsCount: 16,
    foundedYear: 2012,
    verified: true,
  },
  {
    id: 'club-sarc-2',
    institutionId: 'inst-sanjivani-1',
    name: 'SARC (Student Alumni Relations Cell)',
    slug: 'sarc-sanjivani',
    category: 'Departmental',
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=120&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
    description: 'Connecting current Sanjivani undergraduates with 20,000+ distinguished global alumni across multinational corporations and startups.',
    instagramHandle: '@sarc_sanjivani',
    facultyAdvisor: 'Dr. M. V. Kulkarni',
    presidentName: 'Aditya Sen',
    membersCount: 96,
    eventsCount: 10,
    foundedYear: 2016,
    verified: true,
  },
  {
    id: 'club-robocon-3',
    institutionId: 'inst-sanjivani-1',
    name: 'Team Robocon & Automation Sanjivani',
    slug: 'robocon-sanjivani',
    category: 'Technical',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=120&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    description: 'Representing Sanjivani in national and international ABU Robocon competitions, building industrial robotic arms, drones, and autonomous rovers.',
    instagramHandle: '@robocon_sanjivani',
    facultyAdvisor: 'Dr. S. V. Bhaskar',
    presidentName: 'Nikhil Patil',
    membersCount: 142,
    eventsCount: 9,
    foundedYear: 2014,
    verified: true,
  },
  {
    id: 'club-cesa-4',
    institutionId: 'inst-sanjivani-1',
    name: 'CESA (Civil Engineering Students Association)',
    slug: 'cesa-sanjivani',
    category: 'Departmental',
    logoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=120&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
    description: 'Departmental society fostering modern civil infrastructure education, GIS surveying workshops, bridge drafting competitions, and site visits.',
    instagramHandle: '@cesa_sanjivani',
    facultyAdvisor: 'Dr. C. L. Jejurkar',
    presidentName: 'Aditi Bhor',
    membersCount: 168,
    eventsCount: 12,
    foundedYear: 2010,
    verified: true,
  },
  {
    id: 'club-ecell-5',
    institutionId: 'inst-sanjivani-1',
    name: 'Sanjivani Entrepreneurship Cell (E-Cell)',
    slug: 'ecell-sanjivani',
    category: 'Cultural',
    logoUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=120&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    description: 'Empowering campus startup founders, facilitating seed grant applications, incubator mentorship, and the annual Sanjivani E-Summit.',
    instagramHandle: '@ecell_sanjivani',
    facultyAdvisor: 'Prof. S. P. Hase',
    presidentName: 'Shreya Joshi',
    membersCount: 88,
    eventsCount: 7,
    foundedYear: 2015,
    verified: true,
  }
];

export const mockClubMembers: ClubMember[] = [
  {
    id: 'cm-1',
    clubId: 'club-sarc-2',
    userId: 'usr-aditi-1',
    user: mockStudents[0],
    team: 'Network Team',
    designation: 'Network Coordinator',
    role: 'CLUB_ADMIN',
    joinedDate: '2025-08-15',
    tenureYear: '2026-27',
    eventsOrganized: 3,
    isActive: true,
  },
  {
    id: 'cm-2',
    clubId: 'club-csi-1',
    userId: 'usr-rohan-2',
    user: mockStudents[1],
    team: 'Executive Board',
    designation: 'Lead Coordinator',
    role: 'CLUB_ADMIN',
    joinedDate: '2024-07-20',
    tenureYear: '2026-27',
    eventsOrganized: 8,
    isActive: true,
  },
  {
    id: 'cm-3',
    clubId: 'club-robocon-3',
    userId: 'usr-tanvi-3',
    user: mockStudents[2],
    team: 'Electronics & Firmware',
    designation: 'Junior Volunteer',
    role: 'CLUB_VOLUNTEER',
    joinedDate: '2025-09-01',
    tenureYear: '2026-27',
    eventsOrganized: 1,
    isActive: true,
  },
];

export const mockEvents: EventItem[] = [
  {
    id: 'evt-ai-workshop-2026',
    clubId: 'club-csi-1',
    clubName: 'CSI & Coding Club Sanjivani',
    clubLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=120&q=80',
    institutionId: 'inst-sanjivani-1',
    title: 'AI Workshop 2026: Generative Agents & LLMs',
    slug: 'ai-workshop-2026',
    tagline: 'Deep dive into autonomous reasoning agents, RAG architectures, and multi-modal models.',
    description: 'An intensive 2-day hands-on workshop organized at Sanjivani College of Engineering. Featuring leading industry research practitioners, students will learn how to build autonomous agents, implement vector semantic search, and deploy production LLM pipelines.',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    venue: 'Seminar Hall 1, Main Administrative Building, Sanjivani Campus',
    isOnline: false,
    startTime: '2026-09-24T14:00:00+05:30',
    endTime: '2026-09-25T18:00:00+05:30',
    registrationDeadline: '2026-09-23T23:59:59+05:30',
    maxCapacity: 200,
    registeredCount: 147,
    attendedCount: 122,
    entryFee: 0,
    eligibility: 'All Sanjivani branches (Civil, Comp, IT, ECE, Mech students welcome)',
    speakers: [
      {
        name: 'Dr. Anand Ramanathan',
        title: 'Staff AI Research Scientist',
        company: 'Google DeepMind',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80',
      },
      {
        name: 'Sneha Kulkarni',
        title: 'Senior LLM Systems Architect',
        company: 'Microsoft Azure AI',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=160&q=80',
      }
    ],
    status: 'PUBLISHED',
    category: 'Workshop',
    facultyApproved: true,
    naacCategory: 'Technical Skills',
    certificateTemplateId: 'tmpl-sanjivani-aiw-2026',
  },
  {
    id: 'evt-technovation-2026',
    clubId: 'club-csi-1',
    clubName: 'CSI & Coding Club Sanjivani',
    clubLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=120&q=80',
    institutionId: 'inst-sanjivani-1',
    title: 'Technovation 2026: 24-Hour State Level Hackathon',
    slug: 'technovation-2026',
    tagline: 'Build innovative solutions for Smart Agriculture, Rural Healthcare, FinTech & Clean Energy.',
    description: 'Sanjivanis flagship 24-hour hackathon bringing together top student developers across Maharashtra with ₹1,25,000 in cash prizes, cloud credits, direct incubation support, and corporate internship fast-tracks.',
    bannerUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    venue: 'Central Computing Facility & Innovation Lab, Sanjivani COE',
    isOnline: false,
    startTime: '2026-10-15T09:00:00+05:30',
    endTime: '2026-10-16T12:00:00+05:30',
    registrationDeadline: '2026-10-08T20:00:00+05:30',
    maxCapacity: 300,
    registeredCount: 260,
    attendedCount: 0,
    entryFee: 100,
    eligibility: 'Teams of 2 to 4 students from engineering & diploma institutions',
    speakers: [
      {
        name: 'Vikramaditya Roy',
        title: 'VP of Engineering',
        company: 'Razorpay',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80',
      }
    ],
    status: 'PUBLISHED',
    category: 'Hackathon',
    facultyApproved: true,
    naacCategory: 'Capability Enhancement',
  },
  {
    id: 'evt-alumni-conclave-2026',
    clubId: 'club-sarc-2',
    clubName: 'SARC (Student Alumni Relations Cell)',
    clubLogo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=120&q=80',
    institutionId: 'inst-sanjivani-1',
    title: 'Sanjivani Global Alumni Leadership Conclave',
    slug: 'sanjivani-alumni-conclave',
    tagline: 'Fireside dialogue with Sanjivani alumni leaders across Silicon Valley, Europe & India.',
    description: 'An exclusive interactive session exploring global engineering opportunities, master’s admissions at top universities abroad, and career acceleration.',
    bannerUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    venue: 'Sanjivani Main Auditorium & YouTube Live',
    isOnline: true,
    meetingLink: 'https://meet.google.com/sanjivani-alumni-live',
    startTime: '2026-08-20T15:30:00+05:30',
    endTime: '2026-08-20T18:00:00+05:30',
    registrationDeadline: '2026-08-19T23:59:00+05:30',
    maxCapacity: 500,
    registeredCount: 480,
    attendedCount: 412,
    entryFee: 0,
    eligibility: 'All Sanjivani students, faculty, and alumni',
    speakers: [
      {
        name: 'Karan Mehra',
        title: 'Principal Software Engineer',
        company: 'Stripe, San Francisco',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80',
      }
    ],
    status: 'COMPLETED',
    category: 'Webinar',
    facultyApproved: true,
    naacCategory: 'Capability Enhancement',
  }
];

export const mockRegistrations: EventRegistration[] = [
  {
    id: 'reg-aditi-aiw-2026',
    eventId: 'evt-ai-workshop-2026',
    userId: 'usr-aditi-1',
    studentName: 'Aditi Bhor',
    studentEmail: 'aditi.bhor26@sanjivani.edu.in',
    studentRollNo: 'SCOE-24-CE-082',
    studentDepartment: 'Civil Engineering',
    ticketToken: 'TKT-AIW26-ADITI-82914',
    registeredAt: '2026-09-18T11:24:00+05:30',
    status: 'REGISTERED',
  },
  {
    id: 'reg-tanvi-aiw-2026',
    eventId: 'evt-ai-workshop-2026',
    userId: 'usr-tanvi-3',
    studentName: 'Tanvi Deshmukh',
    studentEmail: 'tanvi.d27@sanjivani.edu.in',
    studentRollNo: 'SCOE-25-ECE-045',
    studentDepartment: 'Electronics & Computer Engineering',
    ticketToken: 'TKT-AIW26-TANVI-19402',
    registeredAt: '2026-09-19T09:12:00+05:30',
    status: 'CHECKED_IN',
    checkedInAt: '2026-09-24T14:08:12+05:30',
    checkedInBy: 'usr-rohan-2',
  },
  {
    id: 'reg-aditi-alumni-2026',
    eventId: 'evt-alumni-conclave-2026',
    userId: 'usr-aditi-1',
    studentName: 'Aditi Bhor',
    studentEmail: 'aditi.bhor26@sanjivani.edu.in',
    studentRollNo: 'SCOE-24-CE-082',
    studentDepartment: 'Civil Engineering',
    ticketToken: 'TKT-ALU26-ADITI-44120',
    registeredAt: '2026-08-10T14:30:00+05:30',
    status: 'CHECKED_IN',
    checkedInAt: '2026-08-20T15:32:45+05:30',
    checkedInBy: 'System Webhook',
  }
];

export const mockIssuedCertificates: IssuedCertificate[] = [
  {
    id: 'cert-aditi-alumni-1',
    certificateNumber: 'SCOE-2026-ALU-0042',
    verificationHash: '9e1c2a8f4b0d3e5a7c8f9b0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c',
    eventId: 'evt-alumni-conclave-2026',
    eventTitle: 'Sanjivani Global Alumni Leadership Conclave',
    clubId: 'club-sarc-2',
    clubName: 'SARC (Student Alumni Relations Cell)',
    clubLogo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=120&q=80',
    userId: 'usr-aditi-1',
    studentName: 'Aditi Bhor',
    studentDepartment: 'Civil Engineering',
    issueDate: '2026-08-21',
    naacCategory: 'Capability Enhancement & Guidance for Competitive Examinations',
    signerName: 'Dr. M. V. Kulkarni & Dr. A. G. Thakur',
    signerTitle: 'Faculty Coordinator, SARC & Director, Sanjivani COE',
  },
  {
    id: 'cert-aditi-hack-2',
    certificateNumber: 'SCOE-2026-CS-0108',
    verificationHash: '4f2d8b1c9a0e3f5a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a',
    eventId: 'evt-technovation-2026',
    eventTitle: 'Technovation State Level Hackathon — Innovation Award',
    clubId: 'club-csi-1',
    clubName: 'CSI & Coding Club Sanjivani',
    clubLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=120&q=80',
    userId: 'usr-aditi-1',
    studentName: 'Aditi Bhor',
    studentDepartment: 'Civil Engineering',
    issueDate: '2026-03-15',
    naacCategory: 'Technical Skills & Competition Excellence',
    signerName: 'Prof. D. B. Kshirsagar',
    signerTitle: 'Faculty Coordinator, Computer Society of India',
  }
];

export const mockRecruitmentApplicants: RecruitmentApplicant[] = [
  {
    id: 'app-1',
    cycleId: 'cycle-sarc-26',
    clubId: 'club-sarc-2',
    studentName: 'Neha Deshpande',
    studentEmail: 'neha.d26@sanjivani.edu.in',
    department: 'Information Technology',
    graduationYear: 2027,
    division: 'B',
    targetTeam: 'Network Team',
    statementOfPurpose: 'Eager to coordinate between Sanjivani alumni worldwide and juniors for mentorship, webinars, and internships.',
    portfolioUrl: 'https://linkedin.com/in/neha-deshpande',
    status: 'APPLIED',
    appliedDate: '2026-09-17',
  },
  {
    id: 'app-2',
    cycleId: 'cycle-sarc-26',
    clubId: 'club-sarc-2',
    studentName: 'Sameer Kulkarni',
    studentEmail: 'sameer.k27@sanjivani.edu.in',
    department: 'Computer Engineering',
    graduationYear: 2028,
    division: 'E',
    targetTeam: 'Design & Social Media',
    statementOfPurpose: 'Proficient in Figma, visual brand design, and video editing. Designed banners for the Sanjivani TechFest.',
    portfolioUrl: 'https://behance.net/sameer-designs',
    status: 'SHORTLISTED',
    appliedDate: '2026-09-16',
    interviewNotes: 'Strong visual portfolio. Impressive typography and motion graphics.',
  },
  {
    id: 'app-3',
    cycleId: 'cycle-sarc-26',
    clubId: 'club-sarc-2',
    studentName: 'Manish Verma',
    studentEmail: 'manish.v26@sanjivani.edu.in',
    department: 'Civil Engineering',
    graduationYear: 2027,
    division: 'C',
    targetTeam: 'Content & Logistics',
    statementOfPurpose: 'Organized civil survey camps and coordinated department guest lectures.',
    status: 'INTERVIEW_SCHEDULED',
    appliedDate: '2026-09-15',
    interviewNotes: 'Scheduled for Friday 4:30 PM in Civil Seminar Room.',
  }
];
